FROM arm64v8/ros:humble-ros-base-jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions python3-rosdep git \
    ros-humble-rviz2 ros-humble-robot-localization ros-humble-slam-toolbox \
    ros-humble-navigation2 ros-humble-nav2-bringup ros-humble-nav2-map-server \
    ros-humble-xacro ros-humble-tf2-tools ros-humble-teleop-twist-keyboard \
    ros-humble-pointcloud-to-laserscan ros-humble-rosidl-generator-dds-idl \
    ros-humble-rosidl-generator-c && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/go2_ws
COPY . /opt/go2_ws/src/go2-nav2-amcl-main
COPY docker/entrypoint.real.sh /usr/local/bin/go2-real-entrypoint
RUN chmod +x /usr/local/bin/go2-real-entrypoint
ENTRYPOINT ["/usr/local/bin/go2-real-entrypoint"]
CMD ["bash"]
