isVerbose: false
timer:
  graphRate: 5.0
  planningRate: 10.0
map:
  isPrebuiltMap: true
  prebuiltMapPath: "prebuilt_maps/icra2024_flat_route_start_trg.pcd"
  isVoxelize: true
  voxelSize: 0.12
trg:
  isPrebuiltTRG: false
  prebuiltTRGPath: "prebuilt_graphs/icra2024_flat_route_start_trg.pcd"
  isUpdate: false
  expandDist: 0.4
  robotSize: 0.3
  sampleNum: 36
  heightThreshold: 0.15
  collisionThreshold: 0.1
  updateCollisionThreshold: 0.1
  safetyFactor: 3.0
  goalTolerance: 0.8
