isVerbose: false
timer:
  graphRate: 5.0
  planningRate: 10.0
map:
  isPrebuiltMap: true
  prebuiltMapPath: "prebuilt_maps/icra2024_sloped_route_start_trg.pcd"
  isVoxelize: true
  voxelSize: 0.08
trg:
  isPrebuiltTRG: false
  prebuiltTRGPath: "prebuilt_graphs/icra2024_sloped_route_dense_b_trg.pcd"
  isUpdate: false
  expandDist: 0.32
  robotSize: 0.18
  sampleNum: 80
  heightThreshold: 0.2
  collisionThreshold: 0.22
  updateCollisionThreshold: 0.22
  safetyFactor: 3.0
  goalTolerance: 0.8
